---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudpipelines/pipeline-base
    tag: latest

params:
  REPO_CONTEXT_URL:
  M2_SETTINGS_REPO_USERNAME:
  M2_SETTINGS_REPO_PASSWORD:

inputs:
  - name: ci-scripts
  - name: code-repo
  - name: version

outputs:
  - name: release-results

run:
  path: ci-scripts/ci/tasks/prepare-release.sh
