---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudpipelines/pipeline-base
    tag: latest

params:
  - GROUP_ID:
  - ARTIFACT_ID:
  - ROUTE:
  - ARTIFACTORY_URL:
  - DEPLOY_TARGET_LABEL:
  - APP_NAME:

inputs:
  - name: ci-scripts
  - name: code-repo
  - name: version

outputs:
  - name: deployment

run:
  path: ci-scripts/ci/tasks/prepare-cf-push.sh
