---
resource_types:
  - name: meta
    type: docker-image
    source:
      repository: swce/metadata-resource

resources:
  - name: meta
    type: meta

  - name: code-repo
    type: git
    source:
      uri: ((code-repo-uri))
      branch: ((code-repo-branch))
      ignore_paths:
        - "spring-petclinic-app/ci"
        - "spring-petclinic-app/docs"
      private_key: ((code-repo-private-key))

  - name: ci-scripts
    type: git
    source:
      uri: ((code-repo-uri))
      branch: ((code-repo-branch))
      paths: ["spring-petclinic-app/ci"]
      private_key: ((code-repo-private-key))

  - name: version
    type: semver
    source:
      initial_version: 1.0.0-rc.0
      driver: git
      uri: ((version-repo-uri))
      branch: ((version-repo-branch))
      file: version
      private_key: ((code-repo-private-key))

jobs:
  - name: unit-test
    plan:
      - get: code-repo
        trigger: true
      - get: ci-scripts
      - task: unit-test
        file: ci-scripts/ci/tasks/unit-test.yml

  - name: build-and-publish
    serial: true
    plan:
      - get: code-repo
        passed: [ unit-test ]
        trigger: true
      - get: ci-scripts
      - get: version
        params: { pre: rc }
      - get: meta
      - task: build-and-publish
        file: ci-scripts/ci/tasks/build-and-publish.yml
        params:
          REPO_CONTEXT_URL: ((repo-context-url))
          M2_SETTINGS_REPO_USERNAME: ((m2-settings-repo-username))
          M2_SETTINGS_REPO_PASSWORD: ((m2-settings-repo-password))
      - put: version
        params: { file: version/version }
      - put: code-repo-tag
        resource: code-repo
        params:
          repository: code-repo
          tag: results/tag.txt
          only_tag: true

  - name: bump-major-version
    serial: true
    plan:
      - put: version
        params: { bump: major, pre: rc }

  - name: bump-minor-version
    serial: true
    plan:
      - put: version
        params: { bump: minor, pre: rc }
